type Query {
	test: String
	loadData: String
	saveData: String
	backupData: String
	# Add restaurants as a queryable object
	"The name of this field is the name of the JSON field for the data"
	restaurants: [Restaurant]!
}

# Start here
# enum Cuisine
# Indian, Italian, Pizza, Japanese, Sushi, Chinese, Mexican, Cuban, Jamaican, Ethiopian, Thai, Vietnamese, Korean

# We'll implement Addresses as well
# street, String
# city, String
# state, String
# zip, String

"The Address type"
type Address {
	"The street field"
	street: String
	city: String
	"Assumes US States"
	state: String

	"""
	This represents either a regular *ZIP* Code
	or the new and fancy __ZIP+4__ Code
	"""
	zip: String
}

# And then bring them together in Restaurant
# Let's implement Restaurants, at a minimal level first:
# id, String, required
# name, String, required
# rating, Int, optional
# cuisine, enum Cuisine
# description, String
# address, Address
type Restaurant {
	id: String!
	name: String!
	description: String
	address: Address
}


# type Calendar {
# 	dayNames: DaysOfTheWeek
# }

# enum DaysOfTheWeek {
# 	SUNDAY
# 	MONDAY
# 	TUESDAY
# 	WEDNESDAY
# 	THURSDAY
# 	FRIDAY
# 	SATURDAY
# }
